---
- name: Copy framework-dependent app to guest
  copy:
    src: "{{ role_path }}/../../framework-dependent-app.1.0.0.deb"
    dest: /home/framework-dependent-app.1.0.0.deb

- name: Install dependencies
  become: true
  apt:
    pkg:
      - gnupg
      - apt-transport-https
      - ca-certificates

- name: Download Microsoft GPG key to keyring
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /usr/share/keyrings/microsoft.gpg
    mode: '0644'

- name: Add Microsoft APT repository (VS Code)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    state: present
    filename: 'microsoft'

- name: Add .NET Core APT repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg]
      https://packages.microsoft.com/repos/microsoft-{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}-prod
      {{ ansible_distribution_release | lower }} main
    filename: "dotnetdev"
    state: present

- name: Install framework-dependent app
  become: true
  apt:
    update_cache: true
    deb: /home/framework-dependent-app.1.0.0.deb
