---
- name: Copy framework-dependent app to guest
  copy:
    src: "{{ role_path }}/../../framework-dependent-app.1.0.0.deb"
    dest: /home/framework-dependent-app.1.0.0.deb

- name: Install dependencies
  become: true
  apt:
    pkg:
      - gnupg
      - apt-transport-https
      - ca-certificates

- name: Download Microsoft GPG key to keyring
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /usr/share/keyrings/microsoft.asc
    mode: '0644'
  when:
    - ansible_distribution == "Debian"

- name: Convert Microsoft GPG key to binary format
  ansible.builtin.command:
    cmd: >
      gpg --output /usr/share/keyrings/microsoft.gpg --dearmor /usr/share/keyrings/microsoft.asc
  args:
    creates: /usr/share/keyrings/microsoft.gpg
  when:
    - ansible_distribution == "Debian"

- name: Add .NET Core APT repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg]
      https://packages.microsoft.com/repos/microsoft-{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}-prod
      {{ ansible_distribution_release | lower }} main
    filename: "dotnetdev"
    state: present
  when:
    - ansible_distribution == "Debian"

# Workaround for Ubuntu 24.04 so that we can install dotnet 9.0
- name: Add dotnet backports PPA
  ansible.builtin.apt_repository:
    repo: "ppa:dotnet/backports"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version in ["22.04", "24.04"]

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version in ["22.04", "24.04"]

- name: Install framework-dependent app
  become: true
  apt:
    update_cache: true
    deb: /home/framework-dependent-app.1.0.0.deb
