---
- name: Copy framework-dependent app to guest
  copy:
    src: "{{ role_path }}/../../framework-dependent-app.1.0.0.rpm"
    dest: /home/framework-dependent-app.1.0.0.rpm

- name: Install self-contained app
  become: true
  yum:
    name: /home/framework-dependent-app.1.0.0.rpm
    state: present
    # We sign RPM packages with a PGP key, but don't export the PGP key yet.
    # Skip GPG checks for now.
    disable_gpg_check: true
