---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  # This list should be roughly kept in sync with the list of
  # OSes for which .NET Core builds packages, as seen at
  # https://dotnet.microsoft.com/download/linux-package-manager/sdk-current
  # There are no Docker images for RHEL, so we can't test that.
  # Not sure about Linux Mint/Suse Enterprise Linux docker images, so they are skipped for now.
  - name: ubuntu.22.04
    image: ubuntu:22.04
  - name: ubuntu.24.04
    image: ubuntu:24.04
  - name: ubuntu.25.04
    image: ubuntu:25.04
  - name: debian.12
    image: debian:12
  - name: fedora.41
    image: fedora:41
  - name: fedora.42
    image: fedora:42
  - name: centos.9
    image: centos:9
  - name: centos.10
    image: centos:10
  - name: opensuse.15.6
    image: opensuse/leap:15.6

provisioner:
  name: ansible
  env:
      ANSIBLE_ROLES_PATH: ../../roles
  lint: |
    set -e
    ansible-lint
  inventory:
    host_vars:
      fedora.30:
        # https://github.com/ansible/ansible/issues/54855
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
verifier:
  name: testinfra
