# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v apt) ]; then apt update && apt install -y python3 sudo bash ca-certificates iproute2 && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python*-dnf bash iproute gcc make libffi-devel zlib-devel wget tar && dnf clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python3 python3-pip sudo bash iproute2 gcc make libffi-devel zlib-devel wget tar && zypper clean -a; fi

RUN python3 -c 'import sys; exit(0) if sys.version_info >= (3,8) else exit(1)' || \
    (echo "Upgrading Python..." && \
     wget https://www.python.org/ftp/python/3.9.18/Python-3.9.18.tgz && \
     tar xzf Python-3.9.18.tgz && cd Python-3.9.18 && \
     ./configure --enable-optimizations && \
     make -j$(nproc) altinstall && \
     ln -sf /usr/local/bin/python3.9 /usr/local/bin/python3)
