name: continuous-integration

on: [push, pull_request]

jobs:
  build_ubuntu:
    name: Build (Ubuntu)
    uses: ./.github/workflows/build-template.yml
    with:
      runs-on: ubuntu

  build_windows:
    name: Build (Windows)
    uses: ./.github/workflows/build-template.yml
    with:
      runs-on: windows

  build_macos:
    name: Build (macOS)
    uses: ./.github/workflows/build-template.yml
    with:
      runs-on: macos

  build_package:
    name: Build Package Matrix
    runs-on: ubuntu-latest
    needs: build_ubuntu
    strategy:
      matrix:
        command: [deb, rpm, zip, tarball]
        framework: ['8.0', '9.0']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "${{ matrix.framework }}.x"
      - name: Download NuGet Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ github.workspace }}/nuget
      - name: Build Package
        run: |
          set -e
          export PATH="$PATH:/$HOME/.dotnet/tools"

          mkdir test
          cd test

          ls -lF ${{ github.workspace }}/nuget/
          echo "<configuration><packageSources><add key='local' value='${{ github.workspace }}/nuget' /></packageSources></configuration>" > NuGet.config
          version=$(cat ${{ github.workspace }}/nuget/version.txt)

          # Install the dotnet-${{ matrix.command }} tool
          dotnet tool install --global dotnet-${{ matrix.command }} --version $version --add-source ${{ github.workspace }}/nuget

          # Create a new console application
          dotnet new console --framework net${{ matrix.framework }}

          # Install and use dotnet ${{ matrix.command }}
          dotnet ${{ matrix.command }} install
          dotnet ${{ matrix.command }} -o ${{ github.workspace }}/packages/
      - name: Publish Packages
        uses: actions/upload-artifact@v4
        with:
          name: build-package-${{ matrix.command }}-${{ matrix.framework }}
          path: ${{ github.workspace }}/packages

  test_macos:
    name: Test (macOS)
    runs-on: macos-latest
    needs: build_package
    strategy:
      matrix:
        framework: ['8.0', '9.0']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-package-tarball-${{ matrix.framework }}
          path: ${{ github.workspace }}/packages
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Extract tarball
        run: |
          ls -lF ${{ github.workspace }}/packages/
          tar xvzf ${{ github.workspace }}/packages/test.1.0.0.tar.gz
      - name: Execute program
        run: dotnet ./test.dll

  publish_nuget:
    name: Publish NuGet
    runs-on: windows-latest
    needs: [test_macos]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Download NuGet Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ github.workspace }}/nuget
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Push NuGet Packages
        run: |
          nuget push "${{ github.workspace }}/nuget/*.nupkg" -Source "https://api.nuget.org/v3/index.json" -ApiKey ${{ secrets.NUGET_API_KEY }}
